service: auction-service

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  - ${file(./src/modules/auction/infra/functions.yml)}

resources:
  - ${file(./src/modules/auction/infra/resources.yml)}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
