service: auction-service

plugins:
  - serverless-esbuild

provider:
  name: aws
  runtime: nodejs14.x

functions:
  - ${file(./src/modules/auction/functions.yml)}

resources:
  - ${file(./src/modules/auction/resources.yml)}

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
