service: auction-service

plugins:
  - serverless-esbuild
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  environment:
    AUCTIONS_TABLE_NAME: ${self:custom.tables.AuctionsTable.name}

functions:
  - ${file(./src/modules/auctions/functions/createAuction.yml)}

resources:
  - ${file(./src/modules/auctions/resources/AuctionsTable.yml)}

custom:
  tables:
    AuctionsTable:
      name: !Ref AuctionsTable
      arn: !GetAtt AuctionsTable.Arn
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node14
    define:
      require.resolve: undefined
    platform: node
    concurrency: 10
