createAuction:
  handler: src/modules/auctions/infra/functions/createAuction.handle
  events:
    - http:
        method: POST
        path: /auctions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - ${self:custom.tables.AuctionsTable.arn}
