getAuctions:
  handler: src/modules/auctions/useCases/getAuctions.handler
  events:
    - http:
        method: GET
        path: /auctions
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
      Resource:
        - ${self:custom.tables.AuctionsTable.arn}
